# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_time', models.DateTimeField(default=None)),
                ('delay', models.IntegerField(default=0)),
                ('number', models.CharField(max_length=16)),
            ],
        ),
    ]
